---
ips:
 - input1
controls:
 - control1

paired: false
genome: /data/zusers/andrewsg/genome/mm10/mm10
chrom: /data/zusers/andrewsg/genome/mm10/mm10.chrom.sizes
sponge_flag: false
path: /data/zusers/andrewsg/chipseq_snakemake/common/
macs_g: mm
matching: false
sort: sort #or path to the update version
split: split #or path to the update version